const STORAGE_KEY = "warhex_language";
const SUPPORTED = ["en", "pt", "es"];

const DICT = {
    en: {
        "language.label": "Language",
        "language.english": "English",
        "language.portuguese": "Portuguese",
        "language.spanish": "Spanish",

        "menu.connectionRejected": "Connection Rejected",
        "menu.connectionDesc1": "We couldn't let you join the server.",
        "menu.connectionDesc2": "The server might be full or temporarily unavailable.",
        "menu.connectionDesc3": "Please try again in a few seconds.",
        "menu.connectionTryAgain": "Try again in a bit!",
        "menu.okay": "Okay",
        "menu.play": "Play",
        "menu.playerName": "Player Name",
        "menu.currentMode": "Current mode",
        "menu.selectMode": "Select mode",
        "menu.mode.ffa.desc": "Free for all",
        "menu.mode.clans.desc": "Play with your clan",
        "menu.mode.overdrive.desc": "Mode with special advantages",
        "menu.mode.sandbox.desc": "Free mode for testing",
        "menu.login": "Login",
        "menu.signUp": "Sign Up",
        "menu.logout": "Logout",
        "menu.myProfile": "My Profile",
        "menu.discord": "Discord",
        "menu.shop": "Shop",
        "menu.default": "Default",
        "menu.use": "Use",
        "menu.yourSkins": "Your Skins",
        "menu.globalRank": "Global Rank",
        "menu.top10Accounts": "Top 10 (accounts)",
        "menu.loadingGlobalTop": "Loading global top...",
        "menu.globalRankUnavailable": "Global rank unavailable now.",
        "menu.globalRankLoadError": "Could not load ranking.",
        "menu.name": "Name",
        "menu.score": "Score",
        "menu.playtimeShort": "Play",
        "menu.kills": "Kills",

        "dialog.accessFeatures": "Access Exclusive Features",
        "dialog.loginReserved": "This feature is reserved for registered players.",
        "dialog.loginPerks": "Login to unlock amazing perks, exclusive skins, and track your stats!",
        "dialog.continueGuest": "Continue as Guest",
        "dialog.createAccount": "Create Account",
        "dialog.createAccountDesc": "Join Warhex.io and unlock exclusive features!",
        "dialog.email": "Email",
        "dialog.nickname": "Nickname",
        "dialog.password": "Password",
        "dialog.signUpDiscord": "Sign up with Discord",
        "dialog.signUpGoogle": "Sign up with Google",
        "dialog.signInDiscord": "Continue with Discord",
        "dialog.signInGoogle": "Continue with Google",
        "dialog.oauthNicknameChoice": "Use your {provider} nickname ({nickname}) for this account?\nPress OK to use it or Cancel to type another.",
        "dialog.discordNicknameChoice": "Use your Discord nickname ({nickname}) for this account?\nPress OK for Discord nickname or Cancel to type another.",
        "dialog.customNicknamePrompt": "Type the nickname you want to use:",
        "dialog.discordJoinPrompt": "Your Discord login worked. Do you want to join the Warhex Discord server now?",
        "dialog.createAccountBtn": "Create Account",
        "dialog.cancel": "Cancel",
        "dialog.loginTitle": "Login",
        "dialog.loginDesc": "Enter your credentials to access your account.",
        "dialog.benefit1": "Leveling System: Gain XP, level up, and unlock rewards like exclusive skins.",
        "dialog.benefit2": "Exclusive Skins: Access special skins tied to your level or achievements.",
        "dialog.benefit3": "Account Stats: Track playtime, kills, and highscores.",
        "dialog.benefit4": "Achievements: Unlock milestones for streaks, levels, or hidden challenges.",
        "dialog.benefit5": "Weekly Leaderboard: Compete weekly and see your rank.",

        "legal.privacyPolicy": "Privacy Policy",
        "legal.termsOfUse": "Terms of Use",
        "legal.about": "About",
        "legal.lastUpdated": "Last updated: February 22, 2026",
        "legal.aboutTagline": "Strategy. Defense. PvP.",

        "stats.highscore": "Highscore",
        "stats.playtime": "Playtime",
        "stats.totalKills": "Total Kills",
        "stats.xp": "XP",
        "stats.maxLevel": "Max Level",

        "game.killedBy": "Killed by",
        "game.time": "Time",
        "game.continue": "Continue",
        "game.areYouThere": "Are you still there?",
        "game.inactiveKick": "You will be kicked for inactivity in:",
        "game.settings": "Settings",
        "game.theme": "Theme:",
        "game.disableGrid": "Disable Grid",
        "game.destroy": "Destroy",
        "game.chatTitle": "Warhex Chat:",
        "game.chatWelcome": "Welcome to Warhex.io",
        "game.message": "Message",
        "game.send": "Send",
        "game.group": "Group",
        "game.groupTroopsOn": "Group Troops On",
        "game.groupTroopsOff": "Group Troops Off",
        "game.menu": "Menu",
        "game.multipleBuildings": "Multiple Buildings",
        "game.totalSelected": "Total selected: {count}",
        "game.unknown": "Unknown",
        "game.destroySell": "Destroy / Sell",
        "profile.title": "My Profile",

        "hud.minimizeExpand": "Minimize / Expand",
        "hud.expandPanel": "Expand panel",
        "hud.minimizePanel": "Minimize panel",
        "hud.expand": "Expand",
        "hud.minimize": "Minimize",
        "hud.unitHelp": "Choose the shape and visual model for your units.",
        "hud.reset": "Reset",
        "hud.close": "Close",
        "hud.keybindHelp": "Click \"Set\" and press a key. If that key is already in use, you'll get a conflict warning.",
        "hud.resetKeybinds": "Reset keybinds",
        "hud.set": "Set",
        "hud.pressKey": "Press key...",
        "hud.clear": "Clear",
        "hud.none": "None",
        "hud.editHelp": "Drag and resize game panels. When finished, save or restore defaults.",
        "hud.models": "Models",
        "hud.keybinds": "Keybinds",
        "hud.save": "Save",
        "hud.factoryDefaults": "Factory defaults",
        "hud.exit": "Exit",
        "hud.previewUpgrades": "HUD Preview - Upgrades",
        "key.group.selection": "Selection",
        "key.group.hud": "HUD",
        "key.group.defense": "Defense",
        "key.group.upgrades": "Upgrades",
        "key.action.selectArmy": "Select Army (Soldier+Tank+Siege)",
        "key.action.selectSoldiersOnly": "Select Only Soldiers",
        "key.action.selectTanksOnly": "Select Only Tanks",
        "key.action.selectSiegeOnly": "Select Only Siege",
        "key.action.selectCommander": "Select / Buy Commander",
        "key.action.selectAllUnits": "Select All Units",
        "key.action.toggleMap": "Toggle Map",
        "key.action.returnToBase": "Return to Base",
        "key.action.viewAllPlayers": "View All Players",
        "key.action.centerBaseView": "Center on Base",
        "key.action.toggleGroupTroops": "Toggle Group Troops",
        "key.action.defensePlacement": "Defense Placement (Hold)",
        "key.action.defenseRemount": "Defense Remount (Hold)",
        "key.action.upgrade1": "Upgrade Slot 1",
        "key.action.upgrade2": "Upgrade Slot 2",
        "key.action.upgrade3": "Upgrade Slot 3",
        "key.action.upgradeDestroy": "Upgrade Destroy / Sell",
        "key.action.upgradeBarracksToggle": "Upgrade Barracks Toggle",

        "error.signupMissing": "Please enter email, nickname and password.",
        "error.nicknameShort": "Nickname must be at least 3 characters long.",
        "error.nicknameInvalid": "Nickname can include letters, numbers, spaces and emojis.",
        "error.signupFailed": "Sign up failed: {message}",
        "success.accountCreated": "Account created! Please check your email to verify your account.",
        "error.signinMissing": "Please enter email and password.",
        "error.loginFailed": "Login failed: {message}",
        "error.discordProviderDisabled": "Discord login is not configured yet. Enable Discord provider in Supabase Auth settings.",
        "error.googleProviderDisabled": "Google login is not configured yet. Enable Google provider in Supabase Auth settings.",
        "error.discordLoginFailed": "Discord login failed: {message}"
    },
    pt: {
        "language.label": "Idioma",
        "language.english": "Inglês",
        "language.portuguese": "Português",
        "language.spanish": "Espanhol",

        "menu.connectionRejected": "Conexão recusada",
        "menu.connectionDesc1": "Não foi possível entrar no servidor.",
        "menu.connectionDesc2": "O servidor pode estar cheio ou temporariamente indisponível.",
        "menu.connectionDesc3": "Tente novamente em alguns segundos.",
        "menu.connectionTryAgain": "Tente novamente daqui a pouco!",
        "menu.okay": "Ok",
        "menu.play": "Jogar",
        "menu.playerName": "Nome do jogador",
        "menu.currentMode": "Modo atual",
        "menu.selectMode": "Selecionar modo",
        "menu.mode.ffa.desc": "Livre para todos",
        "menu.mode.clans.desc": "Jogue com seu cla",
        "menu.mode.overdrive.desc": "Modo com vantagens especiais",
        "menu.mode.sandbox.desc": "Modo livre para testar",
        "menu.login": "Entrar",
        "menu.signUp": "Cadastrar",
        "menu.logout": "Sair",
        "menu.myProfile": "Meu perfil",
        "menu.discord": "Discord",
        "menu.shop": "Loja",
        "menu.default": "Padrão",
        "menu.use": "Usar",
        "menu.yourSkins": "Suas skins",
        "menu.globalRank": "Rank Global",
        "menu.top10Accounts": "Top 10 (contas)",
        "menu.loadingGlobalTop": "Carregando rank global...",
        "menu.globalRankUnavailable": "Rank global indisponível agora.",
        "menu.globalRankLoadError": "Não foi possível carregar o ranking.",
        "menu.name": "Nome",
        "menu.score": "Pontos",
        "menu.playtimeShort": "Tempo",
        "menu.kills": "Abates",

        "dialog.accessFeatures": "Acesse recursos exclusivos",
        "dialog.loginReserved": "Este recurso é reservado para jogadores registrados.",
        "dialog.loginPerks": "Entre para desbloquear vantagens, skins exclusivas e acompanhar suas estatísticas!",
        "dialog.continueGuest": "Continuar como convidado",
        "dialog.createAccount": "Criar conta",
        "dialog.createAccountDesc": "Entre no Warhex.io e desbloqueie recursos exclusivos!",
        "dialog.email": "E-mail",
        "dialog.nickname": "Apelido",
        "dialog.password": "Senha",
        "dialog.signUpDiscord": "Cadastrar com Discord",
        "dialog.signUpGoogle": "Cadastrar com Google",
        "dialog.signInDiscord": "Entrar com Discord",
        "dialog.signInGoogle": "Entrar com Google",
        "dialog.oauthNicknameChoice": "Quer usar seu nick do {provider} ({nickname}) nesta conta?\nOK para usar ou Cancelar para escolher outro.",
        "dialog.discordNicknameChoice": "Quer usar seu nick do Discord ({nickname}) nesta conta?\nOK para usar o Discord ou Cancelar para escolher outro.",
        "dialog.customNicknamePrompt": "Digite o nick que voce quer usar:",
        "dialog.discordJoinPrompt": "Seu login com Discord funcionou. Deseja entrar no servidor do Discord do Warhex agora?",
        "dialog.createAccountBtn": "Criar conta",
        "dialog.cancel": "Cancelar",
        "dialog.loginTitle": "Entrar",
        "dialog.loginDesc": "Digite suas credenciais para acessar sua conta.",
        "dialog.benefit1": "Sistema de nivel: Ganhe XP, suba de nivel e desbloqueie recompensas como skins exclusivas.",
        "dialog.benefit2": "Skins exclusivas: Acesse skins especiais ligadas ao seu nivel ou conquistas.",
        "dialog.benefit3": "Estatisticas da conta: Acompanhe tempo de jogo, abates e recordes.",
        "dialog.benefit4": "Conquistas: Desbloqueie marcos por sequencias, niveis ou desafios ocultos.",
        "dialog.benefit5": "Ranking semanal: Compita toda semana e veja sua posicao.",

        "legal.privacyPolicy": "Política de Privacidade",
        "legal.termsOfUse": "Termos de Uso",
        "legal.about": "Sobre",
        "legal.lastUpdated": "Última atualização: 22 de fevereiro de 2026",
        "legal.aboutTagline": "Estratégia. Defesa. PvP.",

        "stats.highscore": "Recorde",
        "stats.playtime": "Tempo jogado",
        "stats.totalKills": "Abates totais",
        "stats.xp": "XP",
        "stats.maxLevel": "Nível máximo",

        "game.killedBy": "Eliminado por",
        "game.time": "Tempo",
        "game.continue": "Continuar",
        "game.areYouThere": "Você ainda está aí?",
        "game.inactiveKick": "Você será removido por inatividade em:",
        "game.settings": "Configurações",
        "game.theme": "Tema:",
        "game.disableGrid": "Desativar grade",
        "game.destroy": "Destruir",
        "game.chatTitle": "Chat Warhex:",
        "game.chatWelcome": "Bem-vindo ao Warhex.io",
        "game.message": "Mensagem",
        "game.send": "Enviar",
        "game.group": "Agrupar",
        "game.groupTroopsOn": "Agrupar tropas ligado",
        "game.groupTroopsOff": "Agrupar tropas desligado",
        "game.menu": "Menu",
        "game.multipleBuildings": "Múltiplas construções",
        "game.totalSelected": "Total selecionado: {count}",
        "game.unknown": "Desconhecido",
        "game.destroySell": "Destruir / Vender",
        "profile.title": "Meu perfil",

        "hud.minimizeExpand": "Minimizar / Expandir",
        "hud.expandPanel": "Expandir painel",
        "hud.minimizePanel": "Minimizar painel",
        "hud.expand": "Expandir",
        "hud.minimize": "Minimizar",
        "hud.unitHelp": "Escolha o formato e o modelo visual das unidades.",
        "hud.reset": "Resetar",
        "hud.close": "Fechar",
        "hud.keybindHelp": "Clique em \"Definir\" e pressione uma tecla. Se a tecla já estiver em uso, você receberá um aviso de conflito.",
        "hud.resetKeybinds": "Resetar teclas",
        "hud.set": "Definir",
        "hud.pressKey": "Pressione...",
        "hud.clear": "Limpar",
        "hud.none": "Nenhuma",
        "hud.editHelp": "Arraste e redimensione os painéis do jogo. Quando terminar, salve ou restaure o padrão.",
        "hud.models": "Modelos",
        "hud.keybinds": "Teclas",
        "hud.save": "Salvar",
        "hud.factoryDefaults": "Padrão de fábrica",
        "hud.exit": "Sair",
        "hud.previewUpgrades": "Prévia HUD - Melhorias",
        "key.group.selection": "Seleção",
        "key.group.hud": "HUD",
        "key.group.defense": "Defesa",
        "key.group.upgrades": "Melhorias",
        "key.action.selectArmy": "Selecionar Exército (Soldado+Tanque+Cerco)",
        "key.action.selectSoldiersOnly": "Selecionar apenas Soldados",
        "key.action.selectTanksOnly": "Selecionar apenas Tanques",
        "key.action.selectSiegeOnly": "Selecionar apenas Cerco",
        "key.action.selectCommander": "Selecionar / Comprar Comandante",
        "key.action.selectAllUnits": "Selecionar todas as unidades",
        "key.action.toggleMap": "Alternar mapa",
        "key.action.returnToBase": "Voltar para base",
        "key.action.viewAllPlayers": "Ver todos jogadores",
        "key.action.centerBaseView": "Centralizar na base",
        "key.action.toggleGroupTroops": "Alternar agrupar tropas",
        "key.action.defensePlacement": "Defesa (segurar)",
        "key.action.defenseRemount": "Remontar defesa (segurar)",
        "key.action.upgrade1": "Melhoria slot 1",
        "key.action.upgrade2": "Melhoria slot 2",
        "key.action.upgrade3": "Melhoria slot 3",
        "key.action.upgradeDestroy": "Melhoria destruir / vender",
        "key.action.upgradeBarracksToggle": "Alternar melhoria quartel",

        "error.signupMissing": "Digite e-mail, apelido e senha.",
        "error.nicknameShort": "O apelido deve ter pelo menos 3 caracteres.",
        "error.nicknameInvalid": "O apelido pode incluir letras, numeros, espacos e emojis.",
        "error.signupFailed": "Cadastro falhou: {message}",
        "success.accountCreated": "Conta criada! Verifique seu e-mail para confirmar.",
        "error.signinMissing": "Digite e-mail e senha.",
        "error.loginFailed": "Falha no login: {message}",
        "error.discordProviderDisabled": "O login com Discord ainda nao esta configurado. Ative o provider Discord no Auth do Supabase.",
        "error.googleProviderDisabled": "O login com Google ainda nao esta configurado. Ative o provider Google no Auth do Supabase.",
        "error.discordLoginFailed": "Falha no login com Discord: {message}"
    },
    es: {
        "language.label": "Idioma",
        "language.english": "Inglés",
        "language.portuguese": "Portugués",
        "language.spanish": "Español",

        "menu.connectionRejected": "Conexión rechazada",
        "menu.connectionDesc1": "No pudimos permitirte entrar al servidor.",
        "menu.connectionDesc2": "El servidor puede estar lleno o temporalmente no disponible.",
        "menu.connectionDesc3": "Inténtalo de nuevo en unos segundos.",
        "menu.connectionTryAgain": "Inténtalo de nuevo en un momento.",
        "menu.okay": "Aceptar",
        "menu.play": "Jugar",
        "menu.playerName": "Nombre del jugador",
        "menu.currentMode": "Modo actual",
        "menu.selectMode": "Seleccionar modo",
        "menu.mode.ffa.desc": "Todos contra todos",
        "menu.mode.clans.desc": "Juega con tu clan",
        "menu.mode.overdrive.desc": "Modo con ventajas especiales",
        "menu.mode.sandbox.desc": "Modo libre para probar",
        "menu.login": "Iniciar sesión",
        "menu.signUp": "Registrarse",
        "menu.logout": "Cerrar sesión",
        "menu.myProfile": "Mi perfil",
        "menu.discord": "Discord",
        "menu.shop": "Tienda",
        "menu.default": "Predeterminado",
        "menu.use": "Usar",
        "menu.yourSkins": "Tus skins",
        "menu.globalRank": "Ranking Global",
        "menu.top10Accounts": "Top 10 (cuentas)",
        "menu.loadingGlobalTop": "Cargando ranking global...",
        "menu.globalRankUnavailable": "Ranking global no disponible ahora.",
        "menu.globalRankLoadError": "No se pudo cargar el ranking.",
        "menu.name": "Nombre",
        "menu.score": "Puntaje",
        "menu.playtimeShort": "Tiempo",
        "menu.kills": "Bajas",

        "dialog.accessFeatures": "Accede a funciones exclusivas",
        "dialog.loginReserved": "Esta función está reservada para jugadores registrados.",
        "dialog.loginPerks": "¡Inicia sesión para desbloquear ventajas, skins exclusivas y seguir tus estadísticas!",
        "dialog.continueGuest": "Continuar como invitado",
        "dialog.createAccount": "Crear cuenta",
        "dialog.createAccountDesc": "¡Únete a Warhex.io y desbloquea funciones exclusivas!",
        "dialog.email": "Correo",
        "dialog.nickname": "Apodo",
        "dialog.signUpDiscord": "Registrarse con Discord",
        "dialog.signUpGoogle": "Registrarse con Google",
        "dialog.signInDiscord": "Iniciar con Discord",
        "dialog.signInGoogle": "Iniciar con Google",
        "dialog.oauthNicknameChoice": "Quieres usar tu nick de {provider} ({nickname}) en esta cuenta?\nOK para usarlo o Cancelar para escribir otro.",
        "dialog.discordNicknameChoice": "Quieres usar tu nick de Discord ({nickname}) en esta cuenta?\nOK para usar Discord o Cancelar para escribir otro.",
        "dialog.customNicknamePrompt": "Escribe el nick que quieres usar:",
        "dialog.discordJoinPrompt": "Tu inicio con Discord funciono. Quieres unirte ahora al servidor de Discord de Warhex?",
        "dialog.password": "Contraseña",
        "dialog.createAccountBtn": "Crear cuenta",
        "dialog.cancel": "Cancelar",
        "dialog.loginTitle": "Iniciar sesión",
        "dialog.loginDesc": "Ingresa tus credenciales para acceder a tu cuenta.",
        "dialog.benefit1": "Sistema de niveles: Gana XP, sube de nivel y desbloquea recompensas como skins exclusivas.",
        "dialog.benefit2": "Skins exclusivas: Accede a skins especiales ligadas a tu nivel o logros.",
        "dialog.benefit3": "Estadisticas de cuenta: Sigue tiempo de juego, bajas y records.",
        "dialog.benefit4": "Logros: Desbloquea hitos por rachas, niveles o desafios ocultos.",
        "dialog.benefit5": "Ranking semanal: Compite cada semana y mira tu posicion.",

        "legal.privacyPolicy": "Política de Privacidad",
        "legal.termsOfUse": "Términos de Uso",
        "legal.about": "Acerca de",
        "legal.lastUpdated": "Última actualización: 22 de febrero de 2026",
        "legal.aboutTagline": "Estrategia. Defensa. PvP.",

        "stats.highscore": "Récord",
        "stats.playtime": "Tiempo jugado",
        "stats.totalKills": "Bajas totales",
        "stats.xp": "XP",
        "stats.maxLevel": "Nivel máximo",

        "game.killedBy": "Eliminado por",
        "game.time": "Tiempo",
        "game.continue": "Continuar",
        "game.areYouThere": "¿Sigues ahí?",
        "game.inactiveKick": "Serás expulsado por inactividad en:",
        "game.settings": "Ajustes",
        "game.theme": "Tema:",
        "game.disableGrid": "Desactivar cuadrícula",
        "game.destroy": "Destruir",
        "game.chatTitle": "Chat Warhex:",
        "game.chatWelcome": "Bienvenido a Warhex.io",
        "game.message": "Mensaje",
        "game.send": "Enviar",
        "game.group": "Agrupar",
        "game.groupTroopsOn": "Agrupar tropas activado",
        "game.groupTroopsOff": "Agrupar tropas desactivado",
        "game.menu": "Menú",
        "game.multipleBuildings": "Múltiples construcciones",
        "game.totalSelected": "Total seleccionado: {count}",
        "game.unknown": "Desconocido",
        "game.destroySell": "Destruir / Vender",
        "profile.title": "Mi perfil",

        "hud.minimizeExpand": "Minimizar / Expandir",
        "hud.expandPanel": "Expandir panel",
        "hud.minimizePanel": "Minimizar panel",
        "hud.expand": "Expandir",
        "hud.minimize": "Minimizar",
        "hud.unitHelp": "Elige la forma y el modelo visual de tus unidades.",
        "hud.reset": "Restablecer",
        "hud.close": "Cerrar",
        "hud.keybindHelp": "Haz clic en \"Asignar\" y presiona una tecla. Si esa tecla ya está en uso, recibirás una advertencia de conflicto.",
        "hud.resetKeybinds": "Restablecer teclas",
        "hud.set": "Asignar",
        "hud.pressKey": "Presiona...",
        "hud.clear": "Limpiar",
        "hud.none": "Ninguna",
        "hud.editHelp": "Arrastra y cambia el tamaño de los paneles del juego. Cuando termines, guarda o restaura los valores predeterminados.",
        "hud.models": "Modelos",
        "hud.keybinds": "Teclas",
        "hud.save": "Guardar",
        "hud.factoryDefaults": "Valores de fábrica",
        "hud.exit": "Salir",
        "hud.previewUpgrades": "Vista previa HUD - Mejoras",
        "key.group.selection": "Selección",
        "key.group.hud": "HUD",
        "key.group.defense": "Defensa",
        "key.group.upgrades": "Mejoras",
        "key.action.selectArmy": "Seleccionar ejército (Soldado+Tanque+Asedio)",
        "key.action.selectSoldiersOnly": "Seleccionar solo Soldados",
        "key.action.selectTanksOnly": "Seleccionar solo Tanques",
        "key.action.selectSiegeOnly": "Seleccionar solo Asedio",
        "key.action.selectCommander": "Seleccionar / Comprar Comandante",
        "key.action.selectAllUnits": "Seleccionar todas las unidades",
        "key.action.toggleMap": "Alternar mapa",
        "key.action.returnToBase": "Volver a la base",
        "key.action.viewAllPlayers": "Ver todos los jugadores",
        "key.action.centerBaseView": "Centrar en la base",
        "key.action.toggleGroupTroops": "Alternar agrupar tropas",
        "key.action.defensePlacement": "Defensa (mantener)",
        "key.action.defenseRemount": "Remontar defensa (mantener)",
        "key.action.upgrade1": "Mejora ranura 1",
        "key.action.upgrade2": "Mejora ranura 2",
        "key.action.upgrade3": "Mejora ranura 3",
        "key.action.upgradeDestroy": "Mejora destruir / vender",
        "key.action.upgradeBarracksToggle": "Alternar mejora barracón",

        "error.signupMissing": "Ingresa correo, apodo y contraseña.",
        "error.nicknameShort": "El apodo debe tener al menos 3 caracteres.",
        "error.nicknameInvalid": "El apodo puede incluir letras, numeros, espacios y emojis.",
        "error.signupFailed": "Registro fallido: {message}",
        "success.accountCreated": "¡Cuenta creada! Revisa tu correo para verificarla.",
        "error.signinMissing": "Ingresa correo y contraseña.",
        "error.loginFailed": "Error de inicio de sesión: {message}",
        "error.discordProviderDisabled": "El inicio con Discord aun no esta configurado. Activa el proveedor Discord en Auth de Supabase.",
        "error.googleProviderDisabled": "El inicio con Google aun no esta configurado. Activa el proveedor Google en Auth de Supabase.",
        "error.discordLoginFailed": "Error de inicio con Discord: {message}"
    }
};

export default class LanguageManager {
    constructor () {
        const stored = this._safeGetStorage(STORAGE_KEY);
        this.language = this._normalizeLanguage(stored) || "en";
    }

    _normalizeLanguage (value) {
        const normalized = (value || "").toLowerCase().trim();
        return SUPPORTED.includes(normalized) ? normalized : null;
    }

    _safeGetStorage (key) {
        try {
            return localStorage.getItem(key);
        } catch {
            return null;
        }
    }

    _safeSetStorage (key, value) {
        try {
            localStorage.setItem(key, value);
        } catch {
            // ignore storage errors
        }
    }

    getLanguage () {
        return this.language;
    }

    setLanguage (lang) {
        const normalized = this._normalizeLanguage(lang);
        if (!normalized) return;
        this.language = normalized;
        this._safeSetStorage(STORAGE_KEY, normalized);
    }

    t (key, vars = {}) {
        const langDict = DICT[this.language] || DICT.en;
        const enDict = DICT.en;
        const template = langDict[key] ?? enDict[key] ?? key;
        return template.replace(/\{(\w+)\}/g, (_, name) => `${vars[name] ?? ""}`);
    }
}


